### ISSUE TITLE
Improve settings for client certificate and key

### ISSUE THREAD

**Issue by jeremycline** [jeremycline/fedora-messaging#2]
I looked into how to set up pika with a client certificate and key, and it's not super user-friendly: https://pika.readthedocs.io/en/latest/examples/using_urlparameters.html#example-connection-urls shows how to create the ssl_options.

We may want to just add a setting in the config for the dictionary you'd normally provide to the URL and generate the proper url-encoded version. Or, since it's just set in stage/prod environments, we just document the process in an SOP. Thoughts?

**Comment by abompard** [comment]
Yeah I agree, adding a JSON url-encoded dict to the URL by hand is very cumbersome.

**Comment by jeremycline** [comment]
Alright, I'll see about adding the settings
